### PR TITLE
Updated Contributors list and Resolved all Conflicts

### PR DESCRIPTION
**Pull request by Zanark**

### CODE REVIEW

**Comment by gaurav-gogia** [comment]
What's a go version shield? It's kinda new for me. Please explain :)

**Comment by Zanark** [comment]
@DesmondANIMUS I added a shield to the README. For more info visit: https://shields.io

**Comment by Zanark** [comment]
@DesmondANIMUS  It's basically a badge for your repo. A badge that shows which language you have used, at-least that's what the one I inserted tells the viewers, you can add your own custom badges too. Visit https://shields.io/#/ and make your own custom badges. ✌🏽

**Comment by gaurav-gogia** [comment]
I see, thanks ^.^

Always good to learn new stuff.

**Pull request merged**
